import {
  Building2,
  Rocket,
  ShoppingBag,
  GraduationCap,
  Search,
  Award,
  FlaskConical,
  ShieldCheck,
  Tag,
  Coins,
  Clock,
  FileCheck2,
  Scale,
  HelpCircle,
  BookOpen,
} from 'lucide-react';

export const PERSONAS = [
  {
    id: 'manufacturer',
    label: 'Manufacturer & Importer',
    labelHi: 'विनिर्माता / आयातक',
    icon: Building2,
    badge: 'Scheme-I & FMCS',
    badgeHi: 'स्कीम-I और एफएमसीएस',
    badgeTone: 'navy',
    description: 'Factory testing, Scheme-I ISI Mark, SIT inspection ledgers & QCO enforcement.',
    descriptionHi: 'फैक्ट्री परीक्षण, स्कीम-I आईएसआई मार्क, एसआईटी निरीक्षण रजिस्टर और अनिवार्य क्यूसीओ।',
    prompts: [
      {
        id: 'bottle_std',
        label: 'Applicable Standard',
        labelHi: 'लागू भारतीय मानक',
        icon: Search,
        query: 'What BIS standard applies to stainless steel water bottles?',
      },
      {
        id: 'scheme_i_proc',
        label: 'Scheme-I Licensing',
        labelHi: 'स्कीम-I लाइसेंस प्रक्रिया',
        icon: Award,
        query: 'What is the 6-step conformity procedure for Scheme-I ISI Mark?',
      },
      {
        id: 'pressure_cooker_qco',
        label: 'QCO Mandatory Status',
        labelHi: 'अनिवार्य क्यूसीओ स्थिति',
        icon: ShieldCheck,
        query: 'Is BIS certification mandatory for pressure cookers under QCO?',
      },
      {
        id: 'helmet_testing',
        label: 'Testing Parameters',
        labelHi: 'परीक्षण आवश्यकताएं',
        icon: FlaskConical,
        query: 'What chemical and mechanical tests are required under IS 4151 for helmets?',
      },
      {
        id: 'electrical_labs',
        label: 'Recognized Labs',
        labelHi: 'मान्यता प्राप्त प्रयोगशालाएं',
        icon: Building2,
        query: 'Which BIS central or recognized laboratories test electrical appliances?',
      },
      {
        id: 'fmcs_scheme',
        label: 'Foreign Importers',
        labelHi: 'विदेशी विनिर्माता योजना',
        icon: Tag,
        query: 'How does the Foreign Manufacturers Certification Scheme (FMCS) work?',
      },
    ],
  },
  {
    id: 'startup_msme',
    label: 'MSME & Startup',
    labelHi: 'एमएसएमई / स्टार्टअप',
    icon: Rocket,
    badge: '50% Fee Relief',
    badgeHi: '50% शुल्क छूट',
    badgeTone: 'amber',
    description: 'Statutory 50% marking fee relief, Option-1 30-day fast-track & ZED testing subsidies.',
    descriptionHi: 'न्यूनतम अंकन शुल्क में 50% छूट, विकल्प-1 30-दिवसीय त्वरित लाइसेंस और ज़ेड सब्सिडी।',
    prompts: [
      {
        id: 'msme_fee',
        label: '50% Fee Relief',
        labelHi: '50% शुल्क छूट',
        icon: Coins,
        query: 'What concessions do startups and MSMEs get on BIS marking fees?',
      },
      {
        id: 'option_1',
        label: 'Option-1 Fast-Track',
        labelHi: '30-दिवसीय त्वरित लाइसेंस',
        icon: Clock,
        query: 'How can a startup get BIS licence in 30 days under Option 1?',
      },
      {
        id: 'zed_subsidy',
        label: 'ZED Testing Subsidy',
        labelHi: 'जेड प्रमाणन सब्सिडी',
        icon: Award,
        query: 'How do I claim 75% to 85% reimbursement under MSME Champions ZED scheme?',
      },
      {
        id: 'form_v_docs',
        label: 'Form-V Checklist',
        labelHi: 'फॉर्म-V आवश्यक दस्तावेज',
        icon: FileCheck2,
        query: 'What documents are required to file Manakonline Form-V for small enterprises?',
      },
      {
        id: 'batch_fee_calc',
        label: 'Marking Fee Calculator',
        labelHi: 'अंकन शुल्क कैलकुलेटर',
        icon: Coins,
        query: 'How do I calculate annual minimum marking fee with 50% MSME concession?',
      },
      {
        id: 'inhouse_lab_sub',
        label: 'Lab Equipment Relief',
        labelHi: 'लैब उपकरण उप-अनुबंध',
        icon: FlaskConical,
        query: 'Can MSMEs sub-contract specific tests if in-house equipment is unavailable?',
      },
    ],
  },
  {
    id: 'consumer',
    label: 'Consumer & Citizen',
    labelHi: 'उपभोक्ता / नागरिक',
    icon: ShoppingBag,
    badge: 'HUID & Rights',
    badgeHi: 'एचयूआईडी व अधिकार',
    badgeTone: 'green',
    description: 'Verify genuine ISI marks, gold 6-digit HUID purity & statutory compensation claims.',
    descriptionHi: 'सोने की 6-अंकीय HUID शुद्धता जांचें, असली ISI मार्क पहचानें और मुआवजा दावा करें।',
    prompts: [
      {
        id: 'gold_huid',
        label: 'Gold Hallmark Check',
        labelHi: 'सोना हॉलमार्क जांच',
        icon: Tag,
        query: 'How do I verify a 6-digit HUID on gold jewellery using BIS Care?',
      },
      {
        id: 'genuine_isi',
        label: 'Verify ISI Mark',
        labelHi: 'असली ISI मार्क जांच',
        icon: ShieldCheck,
        query: 'How can I verify if an ISI mark on a helmet or cylinder is authentic?',
      },
      {
        id: 'defective_comp',
        label: 'Section 19 Claim',
        labelHi: 'धारा 19 उपभोक्ता मुआवजा',
        icon: Scale,
        query: 'I bought a sub-standard ISI product, can I claim compensation under Section 19?',
      },
      {
        id: 'helpline_1915',
        label: 'File Complaint',
        labelHi: 'शिकायत दर्ज करें',
        icon: HelpCircle,
        query: 'How do I file a complaint on e-BIS or National Consumer Helpline 1915?',
      },
      {
        id: 'mandatory_districts',
        label: 'Hallmark Districts',
        labelHi: '343 हॉलमार्क जिले',
        icon: Building2,
        query: 'Which 343 districts in India have mandatory gold hallmarking?',
      },
      {
        id: 'silver_purity',
        label: 'Silver Hallmarking',
        labelHi: 'चांदी हॉलमार्क मानक',
        icon: Award,
        query: 'What purity grades and fineness standards apply to silver under IS 2112?',
      },
    ],
  },
  {
    id: 'student',
    label: 'Student & Educator',
    labelHi: 'छात्र / शिक्षक',
    icon: GraduationCap,
    badge: '₹1 Lakh Grants',
    badgeHi: '₹1 लाख लैब अनुदान',
    badgeTone: 'blue',
    description: 'BIS Standards Clubs, Learning Science via Standards (LSVS) & NITS Lead Auditor training.',
    descriptionHi: 'स्कूलों/कॉलेजों में मानक क्लब, विज्ञान प्रयोग (LSVS) और ₹1,00,000 लैब अपग्रेड अनुदान।',
    prompts: [
      {
        id: 'start_club',
        label: 'Start Standards Club',
        labelHi: 'मानक क्लब की शुरुआत',
        icon: BookOpen,
        query: 'How can our school or college start a BIS Standards Club?',
      },
      {
        id: 'lab_grant_1lakh',
        label: '₹1 Lakh Lab Grant',
        labelHi: '₹1,00,000 लैब अनुदान',
        icon: Coins,
        query: 'What is the procedure to receive the ₹1,00,000 science lab upgradation grant?',
      },
      {
        id: 'lsvs_science',
        label: 'Learning Science (LSVS)',
        labelHi: 'मानकों से विज्ञान सीखें',
        icon: FlaskConical,
        query: 'What physics and chemistry experiments are covered under LSVS for students?',
      },
      {
        id: 'nits_internships',
        label: 'NITS Internships',
        labelHi: 'NITS ग्रीष्मकालीन इंटर्नशिप',
        icon: Award,
        query: 'Does NITS NOIDA offer summer internships and research dissertations for students?',
      },
      {
        id: 'mentor_honorarium',
        label: 'Teacher Mentor Role',
        labelHi: 'शिक्षक मेंटर मानदेय',
        icon: GraduationCap,
        query: 'What are the roles and ₹3,000 honorarium for Standards Club teacher-mentors?',
      },
      {
        id: 'quality_ambassador',
        label: 'Quality Ambassador',
        labelHi: 'क्वालिटी एंबेसडर बैज',
        icon: ShieldCheck,
        query: 'How can students participate in standard writing competitions and get certified?',
      },
    ],
  },
];
