"""Curated Master Registry of Bureau of Indian Standards (BIS) Standards across all 15 Division Councils.

Covers major mandatory certification items (Scheme I - ISI Mark, Scheme II - CRS, Hallmarking),
Quality Control Orders (QCOs), and foundational Indian Standards.
"""
from typing import List, Dict, Any

MASTER_BIS_STANDARDS: List[Dict[str, Any]] = [
    # -------------------------------------------------------------
    # 1. MECHANICAL & CONSUMER GOODS (MED)
    # -------------------------------------------------------------
    {
        "standard_number": "IS 2347:2017",
        "title": "Domestic Pressure Cookers — Specification",
        "product": "Domestic Pressure Cooker",
        "category": "Consumer Goods / Kitchenware",
        "document_type": "Indian Standard",
        "version": "2017",
        "status": "Published",
        "metadata": {
            "division": "MED (Mechanical Engineering)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Domestic Pressure Cookers (Quality Control) Order",
            "keywords": ["pressure cooker", "cooker", "domestic pressure cooker", "kitchen cooker", "whistle cooker"],
        },
    },
    {
        "standard_number": "IS 4151:2020",
        "title": "Protective Helmets for Two-Wheeler Riders — Specification",
        "product": "Two-Wheeler Helmet",
        "category": "Consumer Safety / Automotive",
        "document_type": "Indian Standard",
        "version": "2020",
        "status": "Published",
        "metadata": {
            "division": "MED (Mechanical Engineering)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Two Wheeler Helmets (Quality Control) Order",
            "keywords": ["helmet", "two-wheeler helmet", "motorcycle helmet", "bike helmet", "crash helmet", "rider helmet"],
        },
    },
    {
        "standard_number": "IS 4246:2002",
        "title": "Domestic Gas Stoves for use with Liquefied Petroleum Gases — Specification",
        "product": "Domestic Gas Stove (LPG Stove)",
        "category": "Consumer Appliances",
        "document_type": "Indian Standard",
        "version": "2002",
        "status": "Published",
        "metadata": {
            "division": "MED (Mechanical Engineering)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Domestic Gas Stoves (Quality Control) Order",
            "keywords": ["gas stove", "lpg stove", "gas cooktop", "domestic gas stove", "burner stove", "chulha"],
        },
    },
    {
        "standard_number": "IS 3196 (Part 1):2013",
        "title": "Welded Low Carbon Steel Gas Cylinders Exceeding 5 Litre Water Capacity for Low Pressure Liquefiable Gases",
        "product": "LPG Gas Cylinder",
        "category": "Industrial / Petroleum Equipment",
        "document_type": "Indian Standard",
        "version": "2013",
        "status": "Published",
        "metadata": {
            "division": "MED (Mechanical Engineering)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Gas Cylinders Rules",
            "keywords": ["lpg cylinder", "gas cylinder", "cooking gas cylinder", "steel cylinder"],
        },
    },
    {
        "standard_number": "IS 17803:2022",
        "title": "Stainless Steel Vacuum Flasks and Insulated Bottles — Specification",
        "product": "Stainless Steel Water Bottle / Vacuum Flask",
        "category": "Consumer Goods / Drinkware",
        "document_type": "Indian Standard",
        "version": "2022",
        "status": "Published",
        "metadata": {
            "division": "MED (Mechanical Engineering)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Insulated Flasks and Containers (Quality Control) Order",
            "keywords": ["water bottle", "stainless steel bottle", "vacuum flask", "insulated bottle", "thermos flask", "flask"],
        },
    },

    # -------------------------------------------------------------
    # 2. ELECTRICAL & POWER EQUIPMENT (ETD)
    # -------------------------------------------------------------
    {
        "standard_number": "IS 374:2019",
        "title": "Electric Ceiling Type Fans and Regulators — Specification",
        "product": "Electric Ceiling Fan",
        "category": "Electrical Appliances",
        "document_type": "Indian Standard",
        "version": "2019",
        "status": "Published",
        "metadata": {
            "division": "ETD (Electrotechnical)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Ceiling Fans (Quality Control) Order / BEE Star Rating Mandatory",
            "keywords": ["ceiling fan", "fan", "electric fan", "bldc fan", "table fan"],
        },
    },
    {
        "standard_number": "IS 694:2010",
        "title": "Polyvinyl Chloride Insulated Unsheathed and Sheathed Cables/Cords with Rigid and Flexible Conductor",
        "product": "PVC Insulated Electric Cables & Wires",
        "category": "Electrical Wiring",
        "document_type": "Indian Standard",
        "version": "2010",
        "status": "Published",
        "metadata": {
            "division": "ETD (Electrotechnical)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Electrical Wires and Cables (Quality Control) Order",
            "keywords": ["electric wire", "cable", "pvc cable", "copper wire", "house wire", "electric cables"],
        },
    },
    {
        "standard_number": "IS 1293:2019",
        "title": "Plugs and Socket-Outlets for Domestic and Similar General Use According to Voltage up to 250V",
        "product": "Plugs and Socket Outlets",
        "category": "Electrical Accessories",
        "document_type": "Indian Standard",
        "version": "2019",
        "status": "Published",
        "metadata": {
            "division": "ETD (Electrotechnical)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Plugs and Socket-Outlets (Quality Control) Order",
            "keywords": ["plug", "socket", "electrical plug", "socket outlet", "power socket", "3-pin plug"],
        },
    },
    {
        "standard_number": "IS 3854:1988",
        "title": "Switches for Domestic and Similar General Purposes — Specification",
        "product": "Domestic Electric Switches",
        "category": "Electrical Accessories",
        "document_type": "Indian Standard",
        "version": "1988",
        "status": "Published",
        "metadata": {
            "division": "ETD (Electrotechnical)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Electrical Accessories (Quality Control) Order",
            "keywords": ["switch", "electric switch", "light switch", "modular switch", "domestic switch"],
        },
    },
    {
        "standard_number": "IS 302 (Part 1):2008",
        "title": "Safety of Household and Similar Electrical Appliances — General Requirements",
        "product": "Household Electrical Appliances (General Safety)",
        "category": "Consumer Electrical Appliances",
        "document_type": "Indian Standard",
        "version": "2008",
        "status": "Published",
        "metadata": {
            "division": "ETD (Electrotechnical)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Electrical Appliances Safety Order",
            "keywords": ["appliances", "electric iron", "immersion heater", "toaster", "microwave", "mixer grinder"],
        },
    },

    # -------------------------------------------------------------
    # 3. ELECTRONICS & IT GOODS (CRS - SCHEME II / LITD)
    # -------------------------------------------------------------
    {
        "standard_number": "IS 13252 (Part 1):2010",
        "title": "Information Technology Equipment — Safety: General Requirements",
        "product": "Laptops, Mobile Phones, Power Adapters, Scanners, Printers",
        "category": "Electronics & IT Equipment",
        "document_type": "Indian Standard",
        "version": "2010",
        "status": "Published",
        "metadata": {
            "division": "LITD (Electronics & IT)",
            "certification_scheme": "Scheme II (CRS - Compulsory Registration Scheme)",
            "mandatory": True,
            "qco_order": "MeitY Electronics and Information Technology Goods (Requirement for Compulsory Registration) Order",
            "keywords": ["laptop", "mobile phone", "smartphone", "power adapter", "charger", "printer", "scanner", "tablet"],
        },
    },
    {
        "standard_number": "IS 16046 (Part 2):2018",
        "title": "Secondary Cells and Batteries Containing Alkaline or Other Non-Acid Electrolytes — Lithium Systems",
        "product": "Lithium-ion Batteries and Cells",
        "category": "Batteries & Power Storage",
        "document_type": "Indian Standard",
        "version": "2018",
        "status": "Published",
        "metadata": {
            "division": "LITD (Electronics & IT)",
            "certification_scheme": "Scheme II (CRS - Compulsory Registration Scheme)",
            "mandatory": True,
            "qco_order": "MeitY CRS Order for Portable Secondary Cells",
            "keywords": ["lithium battery", "li-ion battery", "phone battery", "laptop battery", "ev battery", "battery cell", "power bank battery", "mobile battery", "mobile phone battery", "battery", "batteries", "lithium-ion battery"],
        },
    },
    {
        "standard_number": "IS 16102 (Part 1):2012",
        "title": "Self-Ballasted LED Lamps for General Lighting Services — Safety Requirements",
        "product": "LED Bulbs / LED Lamps",
        "category": "Lighting & Electronics",
        "document_type": "Indian Standard",
        "version": "2012",
        "status": "Published",
        "metadata": {
            "division": "LITD (Electronics & IT)",
            "certification_scheme": "Scheme II (CRS - Compulsory Registration Scheme)",
            "mandatory": True,
            "qco_order": "MeitY CRS Order for Self-Ballasted LED Lamps",
            "keywords": ["led bulb", "led lamp", "led light", "bulb", "tube light"],
        },
    },
    {
        "standard_number": "IS 16242 (Part 1):2014",
        "title": "Uninterruptible Power Systems (UPS) — General and Safety Requirements",
        "product": "UPS / Inverter",
        "category": "Electronics & Power Backup",
        "document_type": "Indian Standard",
        "version": "2014",
        "status": "Published",
        "metadata": {
            "division": "LITD (Electronics & IT)",
            "certification_scheme": "Scheme II (CRS - Compulsory Registration Scheme)",
            "mandatory": True,
            "qco_order": "MeitY CRS Order for Inverters and UPS",
            "keywords": ["ups", "inverter", "power backup", "solar inverter"],
        },
    },

    # -------------------------------------------------------------
    # 4. FOOD & AGRICULTURE (FAD)
    # -------------------------------------------------------------
    {
        "standard_number": "IS 14543:2016",
        "title": "Packaged Drinking Water (Other Than Packaged Natural Mineral Water) — Specification",
        "product": "Packaged Drinking Water (Bottled Water)",
        "category": "Food & Beverages",
        "document_type": "Indian Standard",
        "version": "2016",
        "status": "Published",
        "metadata": {
            "division": "FAD (Food & Agriculture)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Food Safety and Standards (Packaging and Labelling) Regulations / Mandatory ISI",
            "keywords": ["packaged drinking water", "bottled water", "drinking water", "bisleri", "packaged water", "water bottle water"],
        },
    },
    {
        "standard_number": "IS 13428:2005",
        "title": "Packaged Natural Mineral Water — Specification",
        "product": "Packaged Natural Mineral Water",
        "category": "Food & Beverages",
        "document_type": "Indian Standard",
        "version": "2005",
        "status": "Published",
        "metadata": {
            "division": "FAD (Food & Agriculture)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Mandatory Certification under FSSAI & BIS Act",
            "keywords": ["mineral water", "natural mineral water", "spring water"],
        },
    },
    {
        "standard_number": "IS 1165:2002",
        "title": "Milk Powder — Specification",
        "product": "Milk Powder",
        "category": "Dairy Products",
        "document_type": "Indian Standard",
        "version": "2002",
        "status": "Published",
        "metadata": {
            "division": "FAD (Food & Agriculture)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Milk and Milk Products Order / Mandatory ISI",
            "keywords": ["milk powder", "dairy powder", "infant milk powder", "skimmed milk powder"],
        },
    },
    {
        "standard_number": "IS 14433:2007",
        "title": "Infant Milk Substitutes — Specification",
        "product": "Infant Milk Substitutes / Baby Food",
        "category": "Dairy & Infant Nutrition",
        "document_type": "Indian Standard",
        "version": "2007",
        "status": "Published",
        "metadata": {
            "division": "FAD (Food & Agriculture)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Infant Milk Substitutes Act / Mandatory ISI",
            "keywords": ["baby food", "infant food", "cerelac", "infant formula", "baby milk"],
        },
    },

    # -------------------------------------------------------------
    # 5. CIVIL ENGINEERING & CONSTRUCTION (CED)
    # -------------------------------------------------------------
    {
        "standard_number": "IS 269:2015",
        "title": "Ordinary Portland Cement — Specification (33, 43 and 53 Grade)",
        "product": "Ordinary Portland Cement (OPC 33, 43, 53)",
        "category": "Construction Materials",
        "document_type": "Indian Standard",
        "version": "2015",
        "status": "Published",
        "metadata": {
            "division": "CED (Civil Engineering)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Cement (Quality Control) Order",
            "keywords": ["cement", "opc cement", "portland cement", "53 grade cement", "43 grade cement", "concrete cement"],
        },
    },
    {
        "standard_number": "IS 456:2000",
        "title": "Plain and Reinforced Concrete — Code of Practice",
        "product": "Plain and Reinforced Concrete (RCC)",
        "category": "Structural Engineering",
        "document_type": "Indian Standard",
        "version": "2000",
        "status": "Published",
        "metadata": {
            "division": "CED (Civil Engineering)",
            "certification_scheme": "National Building Code Baseline",
            "mandatory": True,
            "qco_order": "Mandatory in Indian National Building Code (NBC)",
            "keywords": ["concrete", "rcc", "reinforced concrete", "plain concrete", "beam design", "column design", "slab"],
        },
    },
    {
        "standard_number": "IS 303:1989",
        "title": "Plywood for General Purposes — Specification",
        "product": "Plywood (MR and BWR Grade)",
        "category": "Building Materials",
        "document_type": "Indian Standard",
        "version": "1989",
        "status": "Published",
        "metadata": {
            "division": "CED (Civil Engineering)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Wood and Wood-Based Products (Quality Control) Order",
            "keywords": ["plywood", "commercial plywood", "bwr plywood", "marine ply", "wooden board"],
        },
    },
    {
        "standard_number": "IS 4985:2021",
        "title": "Unplasticized Polyvinyl Chloride (uPVC) Pipes for Potable Water Supplies",
        "product": "uPVC Pipes for Water Supply",
        "category": "Plumbing & Piping",
        "document_type": "Indian Standard",
        "version": "2021",
        "status": "Published",
        "metadata": {
            "division": "CED (Civil Engineering)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "PVC Pipes (Quality Control) Order",
            "keywords": ["pvc pipe", "upvc pipe", "water pipe", "plumbing pipe", "potable water pipe"],
        },
    },

    # -------------------------------------------------------------
    # 6. METALLURGICAL & STEEL (MTD)
    # -------------------------------------------------------------
    {
        "standard_number": "IS 1786:2008",
        "title": "High Strength Deformed Steel Bars and Wires for Concrete Reinforcement (TMT Steel Bars)",
        "product": "TMT Steel Bars / Saria",
        "category": "Steel & Metallurgy",
        "document_type": "Indian Standard",
        "version": "2008",
        "status": "Published",
        "metadata": {
            "division": "MTD (Metallurgical Engineering)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Steel and Steel Products (Quality Control) Order",
            "keywords": ["tmt bar", "tmt steel", "saria", "reinforcement steel", "deformed bar", "fe 500", "fe 550", "steel rebar"],
        },
    },
    {
        "standard_number": "IS 2062:2011",
        "title": "Hot Rolled Medium and High Tensile Structural Steel — Specification",
        "product": "Structural Steel (Beams, Channels, Angles, Plates)",
        "category": "Steel & Metallurgy",
        "document_type": "Indian Standard",
        "version": "2011",
        "status": "Published",
        "metadata": {
            "division": "MTD (Metallurgical Engineering)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Ministry of Steel Quality Control Order",
            "keywords": ["structural steel", "steel beam", "girders", "steel angles", "steel plates", "hot rolled steel"],
        },
    },
    {
        "standard_number": "IS 277:2018",
        "title": "Galvanized Steel Sheets (Plain and Corrugated) — Specification",
        "product": "Galvanized Steel Sheets (Tin Roofing)",
        "category": "Steel & Metallurgy",
        "document_type": "Indian Standard",
        "version": "2018",
        "status": "Published",
        "metadata": {
            "division": "MTD (Metallurgical Engineering)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Steel Sheets Quality Control Order",
            "keywords": ["galvanized sheet", "tin sheet", "corrugated sheet", "roofing sheet", "gi sheet"],
        },
    },

    # -------------------------------------------------------------
    # 7. CHEMICAL & TOYS (CHD)
    # -------------------------------------------------------------
    {
        "standard_number": "IS 9873 (Part 1):2019",
        "title": "Safety of Toys — Part 1: Safety Aspects Related to Mechanical and Physical Properties",
        "product": "Children Toys (Mechanical and Physical Safety)",
        "category": "Toys & Child Safety",
        "document_type": "Indian Standard",
        "version": "2019",
        "status": "Published",
        "metadata": {
            "division": "CHD (Chemical)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Toys (Quality Control) Order, 2020",
            "keywords": ["toys", "children toys", "plastic toys", "dolls", "action figures", "stuffed toys"],
        },
    },
    {
        "standard_number": "IS 2888:2004",
        "title": "Toilet Soap — Specification",
        "product": "Toilet Soap / Bathing Soap",
        "category": "Personal Care",
        "document_type": "Indian Standard",
        "version": "2004",
        "status": "Published",
        "metadata": {
            "division": "CHD (Chemical)",
            "certification_scheme": "Scheme I (Voluntary / ISI available)",
            "mandatory": False,
            "keywords": ["soap", "toilet soap", "bathing soap", "beauty soap", "tfm in soap"],
        },
    },
    {
        "standard_number": "IS 17424:2020",
        "title": "Hand Sanitizer (Alcohol Based) — Specification",
        "product": "Alcohol Based Hand Sanitizer",
        "category": "Personal Hygiene / Healthcare",
        "document_type": "Indian Standard",
        "version": "2020",
        "status": "Published",
        "metadata": {
            "division": "CHD (Chemical)",
            "certification_scheme": "Scheme I (ISI Mark - Recognized)",
            "mandatory": False,
            "keywords": ["sanitizer", "hand sanitizer", "alcohol sanitizer", "disinfectant rub"],
        },
    },

    # -------------------------------------------------------------
    # 8. PETROLEUM & FUELS (PCD)
    # -------------------------------------------------------------
    {
        "standard_number": "IS 1460:2017",
        "title": "Automotive Diesel Fuel — Specification (BS VI)",
        "product": "Automotive Diesel Fuel",
        "category": "Petroleum Fuels",
        "document_type": "Indian Standard",
        "version": "2017",
        "status": "Published",
        "metadata": {
            "division": "PCD (Petroleum, Coal and Related Products)",
            "certification_scheme": "Statutory Bharat Stage VI Mandatory Compliance",
            "mandatory": True,
            "qco_order": "Ministry of Petroleum & Natural Gas BS VI Emission Norms",
            "keywords": ["diesel", "automotive diesel", "high speed diesel", "hsd", "diesel fuel", "cetane number"],
        },
    },
    {
        "standard_number": "IS 2796:2017",
        "title": "Motor Gasoline — Specification (BS VI and Ethanol Blended E10, E20)",
        "product": "Motor Gasoline (Petrol)",
        "category": "Petroleum Fuels",
        "document_type": "Indian Standard",
        "version": "2017",
        "status": "Published",
        "metadata": {
            "division": "PCD (Petroleum, Coal and Related Products)",
            "certification_scheme": "Statutory Bharat Stage VI Mandatory Compliance",
            "mandatory": True,
            "qco_order": "Ministry of Petroleum & Natural Gas Ethanol Blending Norms",
            "keywords": ["petrol", "gasoline", "motor spirit", "e20 petrol", "octane", "ron 91", "ron 95"],
        },
    },
    {
        "standard_number": "IS 4576:1999",
        "title": "Liquefied Petroleum Gases — Specification",
        "product": "Liquefied Petroleum Gas (LPG Fuel)",
        "category": "Petroleum Fuels",
        "document_type": "Indian Standard",
        "version": "1999",
        "status": "Published",
        "metadata": {
            "division": "PCD (Petroleum, Coal and Related Products)",
            "certification_scheme": "Mandatory Petroleum Product Standard",
            "mandatory": True,
            "keywords": ["lpg", "cooking gas", "liquefied petroleum gas", "propane butane"],
        },
    },

    # -------------------------------------------------------------
    # 9. GOLD & SILVER HALLMARKING (HMD)
    # -------------------------------------------------------------
    {
        "standard_number": "IS 1417:2016",
        "title": "Gold and Gold Alloys, Jewellery/Artefacts — Fineness and Marking",
        "product": "Gold Jewellery and Artefacts (Hallmarking)",
        "category": "Precious Metals / Jewellery",
        "document_type": "Indian Standard",
        "version": "2016",
        "status": "Published",
        "metadata": {
            "division": "HMD (Hallmarking)",
            "certification_scheme": "Mandatory Gold Hallmarking Order (HUID)",
            "mandatory": True,
            "qco_order": "Hallmarking of Gold Jewellery and Gold Artefacts Order",
            "keywords": ["gold", "gold jewellery", "hallmark", "huid", "22k gold", "18k gold", "14k gold", "gold purity"],
        },
    },
    {
        "standard_number": "IS 2112:2014",
        "title": "Silver and Silver Alloys, Jewellery/Artefacts — Fineness and Marking",
        "product": "Silver Jewellery and Artefacts",
        "category": "Precious Metals / Jewellery",
        "document_type": "Indian Standard",
        "version": "2014",
        "status": "Published",
        "metadata": {
            "division": "HMD (Hallmarking)",
            "certification_scheme": "Silver Hallmarking Scheme",
            "mandatory": False,
            "keywords": ["silver", "silver jewellery", "silver hallmark", "chandi", "silver utensils"],
        },
    },

    # -------------------------------------------------------------
    # 10. MEDICAL DEVICES (MHD)
    # -------------------------------------------------------------
    {
        "standard_number": "IS 3055 (Part 1):1994",
        "title": "Clinical Thermometers — Specification",
        "product": "Clinical Thermometers",
        "category": "Medical Devices",
        "document_type": "Indian Standard",
        "version": "1994",
        "status": "Published",
        "metadata": {
            "division": "MHD (Medical Equipment)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Medical Devices Quality Control Order",
            "keywords": ["thermometer", "clinical thermometer", "digital thermometer", "body temperature"],
        },
    },
    {
        "standard_number": "IS 4148:1989",
        "title": "Surgical Rubber Gloves — Specification",
        "product": "Surgical Gloves / Examination Gloves",
        "category": "Medical Consumables",
        "document_type": "Indian Standard",
        "version": "1989",
        "status": "Published",
        "metadata": {
            "division": "MHD (Medical Equipment)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Surgical Rubber Gloves (Quality Control) Order",
            "keywords": ["surgical gloves", "medical gloves", "rubber gloves", "latex gloves"],
        },
    },
    {
        "standard_number": "IS 11004 (Part 1):2021",
        "title": "Male Condoms — Specification — Part 1: Condoms Made from Natural Rubber Latex",
        "product": "Male Latex Condoms",
        "category": "Medical Devices / Contraceptives",
        "document_type": "Indian Standard",
        "version": "2021",
        "status": "Published",
        "metadata": {
            "division": "MHD (Medical Equipment & Hospital Planning)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory under Drugs and Cosmetics Act)",
            "mandatory": True,
            "qco_order": "Medical Devices and Contraceptives Regulatory Standards",
            "keywords": ["condom", "condoms", "male condom", "latex condom", "contraceptive", "rubber condom", "nirodh", "male latex condoms"],
        },
    },

    # -------------------------------------------------------------
    # 11. TEXTILES & PROTECTIVE WEAR (TXD)
    # -------------------------------------------------------------
    {
        "standard_number": "IS 9473:2002",
        "title": "Respiratory Protective Devices — Filtering Half Masks to Protect Against Particles",
        "product": "Respiratory Face Masks (N95 / FFP2 / FFP3)",
        "category": "Protective Equipment / Textiles",
        "document_type": "Indian Standard",
        "version": "2002",
        "status": "Published",
        "metadata": {
            "division": "TXD (Textiles)",
            "certification_scheme": "Scheme I (ISI Mark - Recognized)",
            "mandatory": True,
            "qco_order": "Protective Textiles (Quality Control) Order",
            "keywords": ["mask", "n95 mask", "face mask", "filtering mask", "respiratory mask", "ffp2 mask"],
        },
    },

    # -------------------------------------------------------------
    # 12. CONSUMER CARE, SAFETY & BUILDING PRODUCTS (EXPANDED)
    # -------------------------------------------------------------
    {
        "standard_number": "IS 6356:2001",
        "title": "Toothpaste — Specification",
        "product": "Toothpaste",
        "category": "Personal Care / Oral Hygiene",
        "document_type": "Indian Standard",
        "version": "2001",
        "status": "Published",
        "metadata": {
            "division": "CHD (Chemical)",
            "certification_scheme": "Scheme I (ISI Mark - Recognized Quality Standard)",
            "mandatory": False,
            "keywords": ["toothpaste", "oral hygiene", "dental cream", "tooth paste", "dentifrice"],
        },
    },
    {
        "standard_number": "IS 15298 (Part 2):2016",
        "title": "Personal Protective Equipment — Part 2: Safety Footwear",
        "product": "Safety Shoes / Industrial Footwear",
        "category": "Protective Equipment / Footwear",
        "document_type": "Indian Standard",
        "version": "2016",
        "status": "Published",
        "metadata": {
            "division": "CHD (Chemical / Leather & Footwear)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Footwear made from Leather and other materials (Quality Control) Order",
            "keywords": ["shoes", "safety shoes", "footwear", "safety boots", "industrial footwear", "leather shoes", "boots"],
        },
    },
    {
        "standard_number": "IS 15683:2018",
        "title": "Portable Fire Extinguishers — Performance and Construction — Specification",
        "product": "Portable Fire Extinguisher",
        "category": "Fire Safety / Safety Equipment",
        "document_type": "Indian Standard",
        "version": "2018",
        "status": "Published",
        "metadata": {
            "division": "CED (Civil Engineering)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Fire Extinguishers (Quality Control) Order",
            "keywords": ["fire extinguisher", "fire safety", "abc extinguisher", "co2 extinguisher", "extinguisher"],
        },
    },
    {
        "standard_number": "IS 14286:2010",
        "title": "Crystalline Silicon Terrestrial Photovoltaic (PV) Modules — Design Qualification and Type Approval",
        "product": "Solar Panels / PV Modules",
        "category": "Renewable Energy / Solar Equipment",
        "document_type": "Indian Standard",
        "version": "2010",
        "status": "Published",
        "metadata": {
            "division": "ETD (Electrotechnical)",
            "certification_scheme": "Scheme II (CRS - Compulsory Registration Scheme)",
            "mandatory": True,
            "qco_order": "MNRE Solar Photovoltaics, Systems, Devices and Components Goods Order",
            "keywords": ["solar panel", "solar module", "pv module", "solar pv", "photovoltaic", "solar cell"],
        },
    },
    {
        "standard_number": "IS 303:1989",
        "title": "Plywood for General Purposes — Specification",
        "product": "Plywood (Commercial / Moisture Resistant)",
        "category": "Wood & Timber Products / Construction",
        "document_type": "Indian Standard",
        "version": "1989",
        "status": "Published",
        "metadata": {
            "division": "CED (Civil Engineering)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Wood Based Boards (Quality Control) Order",
            "keywords": ["plywood", "ply", "commercial ply", "mr grade ply", "wooden board"],
        },
    },
    {
        "standard_number": "IS 15622:2017",
        "title": "Pressed Ceramic Tiles — Specification",
        "product": "Ceramic Tiles / Vitrified Tiles",
        "category": "Building Materials / Flooring",
        "document_type": "Indian Standard",
        "version": "2017",
        "status": "Published",
        "metadata": {
            "division": "CED (Civil Engineering)",
            "certification_scheme": "Scheme I (ISI Mark - Mandatory)",
            "mandatory": True,
            "qco_order": "Ceramic Tiles (Quality Control) Order",
            "keywords": ["tiles", "ceramic tiles", "vitrified tiles", "floor tiles", "wall tiles"],
        },
    },
]
